# Generated by Django 4.2.21 on 2025-05-18 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import watch_control_app.models.watch
import watch_control_app.models.work_time_period


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMemeber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_name', models.CharField(max_length=256, verbose_name='Имя члена экипажа')),
                ('cm_surname', models.CharField(max_length=256, verbose_name='Фамилия члена экипажа')),
                ('cm_patronymic', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество члена экипажа')),
                ('cm_course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс члена экипажа')),
                ('cm_birthday', models.DateField(verbose_name='День рождения члена экипажа')),
                ('cm_status', models.BooleanField(default=True, verbose_name='Активен')),
                ('cm_sex', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=128, verbose_name='Пол члена экипажа')),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Члены экипажа',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=256, verbose_name='Наименования палубы')),
                ('d_prioriter', models.PositiveIntegerField(default=999, verbose_name='Приоритет палубы')),
                ('d_svg', models.FileField(upload_to='decks/', verbose_name='SVG судная')),
            ],
            options={
                'verbose_name': 'Палуба Седова',
                'verbose_name_plural': 'Палубы Седова',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=256, verbose_name='Наименование Учебного заведения')),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=256, verbose_name='Наименование должности пользователя')),
                ('P_priority', models.PositiveIntegerField(default=999, verbose_name='Приоритет должности')),
            ],
            options={
                'verbose_name': 'Должность пользователя',
                'verbose_name_plural': 'Должности пользователей',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=256, verbose_name='Наименование роли пользователя')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_start_date', models.DateField(default=datetime.date.today, verbose_name='Дата начала вахты')),
                ('w_end_date', models.DateField(default=watch_control_app.models.watch.default_end_date, verbose_name='Дата конца вахты')),
            ],
            options={
                'verbose_name': 'Вахта',
                'verbose_name_plural': 'Вахты',
            },
        ),
        migrations.CreateModel(
            name='WorkTimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wti_name', models.CharField(max_length=256, verbose_name='Наименование смены')),
                ('wti_prioritet', models.PositiveIntegerField(default=999, verbose_name='Приоритет смены')),
            ],
            options={
                'verbose_name': 'Смена на вахте',
                'verbose_name_plural': 'Смены на вахте',
            },
        ),
        migrations.CreateModel(
            name='WorkTimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtp_name', models.CharField(max_length=256, verbose_name='Наименование временного промежутка смены')),
                ('wtp_start_time', models.TimeField(default=datetime.datetime.now, verbose_name='Начала временного промежутка')),
                ('wtp_end_time', models.TimeField(default=watch_control_app.models.work_time_period.get_default_work_time_period, verbose_name='Конец временного промежутка')),
                ('wtp_work_time_interval', models.ManyToManyField(blank=True, to='watch_control_app.worktimeinterval', verbose_name='Смены')),
            ],
            options={
                'verbose_name': 'Временной промежуток смены',
                'verbose_name_plural': 'Временные промежутки смены',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('patronymic', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество пользователя')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.post', verbose_name='Должность пользователя')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.role', verbose_name='Роли пользователя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeckPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(max_length=256, verbose_name='Наименование места на палубе')),
                ('dp_svg_name', models.CharField(max_length=256, verbose_name='Наименование места в SVG файле')),
                ('dp_svg_id', models.CharField(max_length=256, verbose_name='Id места в SVG файле')),
                ('dp_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_control_app.deck', verbose_name='Палуба')),
            ],
            options={
                'verbose_name': 'Место на палубе',
                'verbose_name_plural': 'Места на палубе',
            },
        ),
        migrations.CreateModel(
            name='DayWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dw_date', models.DateField(verbose_name='Дата дня вахты')),
                ('dw_crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_control_app.crewmemeber', verbose_name='Член экипажа')),
                ('dw_deck_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.deckplace', verbose_name='Место на палубе')),
                ('dw_time_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.worktimeinterval', verbose_name='Смена')),
                ('dw_watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_control_app.watch', verbose_name='вахта')),
            ],
            options={
                'verbose_name': 'День вахты',
                'verbose_name_plural': 'Дни вахты',
            },
        ),
        migrations.AddField(
            model_name='crewmemeber',
            name='cm_institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.institution', verbose_name='Учебное заведение члена экипажа'),
        ),
        migrations.AddField(
            model_name='crewmemeber',
            name='cm_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.post', verbose_name='Должность члена экипажа'),
        ),
    ]
