# Generated by Django 4.2.21 on 2025-05-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_control_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckplace',
            name='dp_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание палубы'),
        ),
        migrations.AlterField(
            model_name='crewmemeber',
            name='cm_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch_control_app.post', verbose_name='Должность члена экипажа'),
        ),
    ]
