# Generated by Django 4.2.21 on 2025-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_control_app', '0002_deckplace_dp_description_alter_crewmemeber_cm_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywatch',
            name='dw_absence',
            field=models.BooleanField(default=False, verbose_name='Отсутсвие члена экипажа'),
        ),
        migrations.AddField(
            model_name='daywatch',
            name='dw_absence_reason',
            field=models.CharField(blank=True, choices=[('Др', 'День рождение'), ('Бо', 'Болезнь'), ('Дг', 'Другое')], max_length=128, null=True, verbose_name='Причина отсутствия'),
        ),
    ]
